services:
  - type: web
    name: la-miu-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        sync: false
      - key: ADMIN_USER
        value: admin001
      - key: ADMIN_PASSWORD
        value: "123456"
